// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhybphxmzlyesdfvusst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoeWJwaHhtemx5ZXNkZnZ1c3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDg0NDQsImV4cCI6MjA1OTU4NDQ0NH0.toAGZG_vrD8kQEd1L_rS8sadD_CTsccQLvRbXx-Gr_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);